# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: KT
email: kaustubh.iitkgp@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Hello World! Its all about code, computers, robots and digital fabrication.
twitter_username: kaustubht08
github_username: hellraiserinchief
minimal_mistakes_skin: default #"default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"

search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes@4.22.0
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Kaustubh Tripathi"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Code.Robot.3D Print.CNC.more.."

  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/kaustubht08/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/hellraiserinchief"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/kaustubht08/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/hellraiserinchief"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

repository: hellraiserinchief/hellraiserinchief.github.io
comments:
  provider: "utterances"
  utterances:
    theme: "github-light" # "github-dark"
    issue_term: "pathname"

